Args = \
  --initialize-at-run-time=io.netty.channel.DefaultFileRegion \
  --initialize-at-run-time=io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe \
  --initialize-at-run-time=io.netty.channel.epoll.AbstractEpollServerChannel \
  --initialize-at-run-time=io.netty.channel.epoll.EpollDatagramChannel \
  --initialize-at-run-time=io.netty.channel.epoll.EpollEventLoop \
  --initialize-at-run-time=io.netty.channel.epoll.EpollEventLoopGroup \
  --initialize-at-run-time=io.netty.channel.epoll.EpollServerSocketChannel \
  --initialize-at-run-time=io.netty.channel.epoll.EpollSocketChannel \
  --initialize-at-run-time=io.netty.channel.epoll.Native \
  --initialize-at-run-time=io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe \
  --initialize-at-run-time=io.netty.channel.kqueue.AbstractKQueueServerChannel \
  --initialize-at-run-time=io.netty.channel.kqueue.KQueueDatagramChannel \
  --initialize-at-run-time=io.netty.channel.kqueue.KQueueEventLoop \
  --initialize-at-run-time=io.netty.channel.kqueue.KQueueEventLoopGroup \
  --initialize-at-run-time=io.netty.channel.kqueue.KQueueServerSocketChannel \
  --initialize-at-run-time=io.netty.channel.kqueue.KQueueSocketChannel \
  --initialize-at-run-time=io.netty.channel.kqueue.Native \
  --initialize-at-run-time=io.netty.channel.unix.Errors \
  --initialize-at-run-time=io.netty.channel.unix.IovArray \
  --initialize-at-run-time=io.netty.channel.unix.Limits \
  --initialize-at-run-time=io.netty.channel.unix.Socket \
  --initialize-at-run-time=io.netty.handler.ssl.AbstractSniHandler \
  --initialize-at-run-time=io.netty.handler.ssl.BoringSSLContext \
  --initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine \
  --initialize-at-run-time=io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator \
  --initialize-at-run-time=io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine \
  --initialize-at-run-time=io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine \
  --initialize-at-run-time=io.netty.handler.ssl.OpenSsl \
  --initialize-at-run-time=io.netty.handler.ssl.OpenSslContext \
  --initialize-at-run-time=io.netty.handler.ssl.OpenSslEngine \
  --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslContext \
  --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine \
  --initialize-at-run-time=io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator \
  --initialize-at-run-time=io.netty.handler.ssl.util.OpenJdkSelfSignedCertGenerator \
  --initialize-at-run-time=io.netty.handler.ssl.util.SelfSignedCertificate \
  --initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger \
  --initialize-at-run-time=ratpack.server.internal.NettyRatpackServer \
  --initialize-at-run-time=ch.qos.logback \
  --initialize-at-run-time=com.zaxxer.hikari \
  --initialize-at-run-time=org.mariadb.jdbc \
