-- Flyway migration script: V20241222214259__createCurrenciesSequenceWithTable.sql
-- Author: Mark Mngoma
-- Created on: 2024-12-22 21:42:59
-- Add your SQL migration statements here.
CREATE SEQUENCE IF NOT EXISTS dboFinance.CURRENCIES_SEQ START WITH 1 INCREMENT BY 1 CACHE 1 NOCYCLE;

CREATE TABLE dboFinance.CURRENCIES (
  ID INT UNSIGNED NOT NULL DEFAULT NEXTVAL(dboFinance.CURRENCIES_SEQ),
  CURRENCY_ID INT UNSIGNED NOT NULL UNIQUE,
  CURRENCY_CODE VARCHAR(3) NOT NULL UNIQUE,
  CURRENCY_NAME VARCHAR(50) NOT NULL,
  CURRENCY_SYMBOL VARCHAR(20) NOT NULL,
  CURRENCY_FLAG VARCHAR(100) NOT NULL,
  ARCHIVED BIT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY INT UNSIGNED NOT NULL,
  UPDATED_AT TIMESTAMP NULL DEFAULT NULL,
  UPDATED_BY INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
