name: Java CI with Gradle

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        version: latest
        compose-file: "./src/test/resources/docker-compose.yml"
      
    - name: Set up GraalVM CE 17
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm-community'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: true

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build and Test with Gradle Wrapper
      run: ./gradlew clean --info test

    - name: Build Shadow JAR
      run: ./gradlew shadowJar

    - name: Build Native Image
      run: ./gradlew nativeCompile

    - name: Upload native binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: reactive-finance-ratpack-native
        path: build/native/nativeCompile/reactive-finance-ratpack
        if-no-files-found: error
